### ISSUE TITLE
LoginAsync throws an IndexOutOfRangeException if you deny the app permissions when signing on.

### ISSUE THREAD

**Issue by andersosthus** [auth0/Auth0.Windows8.Cs#4]
I get a IndexOutOfRangeException when I click "no" on the screen where I have to consent to the permissions requested.

I suspect this is due to no checking of the input to the ```parseResult``` method. I guess either a "LoginCanceld" type of object, or a property with "canceled" could be a better solution here.

```
   at Auth0.SDK.Auth0Client.parseResult(String result)
   at Auth0.SDK.Auth0Client.<LoginAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at UXRisk.Services.Authentication.Auth0AuthenticationContext.<CallLoginAsync>d__e.MoveNext()
```
![auth0exception](https://cloud.githubusercontent.com/assets/184104/5814069/70a75b10-a087-11e4-95c6-7000a76d94d6.png)

**Comment by siacomuzzi** [comment]
Fixed @ [Auth0.Windows8.Cs v1.3.0](https://www.nuget.org/packages/Auth0.Windows8.Cs)

If the user pressed the back button `LoginAsync` throws a `AuthenticationCancelException`. If consent was not given (on social providers) or some other error happened it will throw a `AuthenticationErrorException`.
